spring.application.name=springboot-mvc-api
spring.h2.console.enabled=true
spring.h2.console.path=/h2console
spring.datasource.url=jdbc:h2:file:/Users/91976/Downloads/db
spring.datasource.username=vikasDB
spring.datasource.password=Vikas123
spring.jpa.hibernate.ddl-auto=update